import mongoose from "mongoose";


const userSchema = new mongoose.Schema({
    coustomerType: String,
    sendPromotions: Boolean,
    vipCoustomer: Boolean,
    title: String,
    firstName: String,
    lastName: String,
    mobile: Number,
    profession: String,
    openningAccountBalance: Number,
    email: String,
    loginPassword: String,
    address1: String,
    address2: String,
    address3: String,
    city: String,
    state: String,
    country: String,
    pincode: Number,
    area: String,
    postOffice: String,
    taluk: String,
    relegion: String,
    branchName: String,
    gender: String,
    dateOfBirth: Date,
    dateOfAnniversary: Date,
    age: Number,
    nameOfNominee: String,
    nomineeRelation: String,
    nomineePhone: Number,
    nomineePanCard: String,
    nomineeVoterId: String,
    nomineeRationCard: String,
    attachPanCard: String,
    attachVoterId: String,
    attachRationCard: String,
    PanCard: String,
    panCardImage: String,
    aadhaarCard: String,
    aadhaarCardImage: String,
    drivingLicense: String,
    drivingLicenseImage: String,
    passport: String,
    passportImage: String,
});

// FIX: Prevent model overwrite
export default mongoose.models.UsersList || mongoose.model("UsersList", userSchema);